# Generated by Django 6.0.1 on 2026-01-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="firebase_uid",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_email_verified",
            field=models.BooleanField(default=False, verbose_name="E-posta Doğrulandı"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_photo_file",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
